export interface JiraIssueParams {
  requirement: string;
  verdict: string;
  scribeNotes: string;
  mustFixIssues: string[];
  sessionId: string;
  projectKey?: string;
  confidenceLevel?: string;
  humanJudgementPoints?: string[];
  assigneeAccountId?: string;
  endorsementType?: 'countersigned' | 'assigned_for_review';
}

export interface JiraMember {
  accountId:    string;
  displayName:  string;
  emailAddress: string;
}

export async function fetchProjectMembers(): Promise<JiraMember[]> {
  const domain     = process.env.JIRA_DOMAIN;
  const email      = process.env.JIRA_EMAIL;
  const token      = process.env.JIRA_API_TOKEN;
  const projectKey = process.env.JIRA_PROJECT_KEY;

  if (!domain || !email || !token || !projectKey) return [];

  try {
    const url = `https://${domain}/rest/api/3/user/assignable/search?project=${projectKey}&maxResults=50`;
    const res = await fetch(url, { headers: buildHeaders(email, token) });
    if (!res.ok) return [];
    const data = (await res.json()) as Array<{ accountId?: string; displayName?: string; emailAddress?: string }>;
    return data
      .filter(u => u.accountId && u.displayName)
      .map(u => ({
        accountId:    u.accountId!,
        displayName:  u.displayName!,
        emailAddress: u.emailAddress ?? '',
      }));
  } catch {
    return [];
  }
}

export interface JiraResult {
  issueKey: string;
  issueUrl: string;
}

function verdictToLabel(verdict: string): string {
  const v = verdict.toLowerCase();
  if (v.includes('condition')) return 'arboard-conditions';
  if (v.includes('revision')) return 'arboard-revision';
  if (v.includes('approv')) return 'arboard-approved';
  return 'arboard-review';
}

function verdictToPriority(verdict: string): 'High' | 'Medium' {
  const v = verdict.toLowerCase();
  return v.includes('condition') || v.includes('revision') ? 'High' : 'Medium';
}

function confidenceToPanelType(level: string): 'success' | 'note' | 'warning' {
  const l = level.toLowerCase();
  if (l.includes('high')) return 'success';
  if (l.includes('medium')) return 'note';
  return 'warning';
}

function buildADF(params: JiraIssueParams): object {
  const { requirement, verdict, scribeNotes, mustFixIssues, sessionId, confidenceLevel, humanJudgementPoints } = params;

  const content: object[] = [
    {
      type: 'heading',
      attrs: { level: 2 },
      content: [{ type: 'text', text: 'Draft Recommendation' }],
    },
    {
      type: 'paragraph',
      content: [{ type: 'text', text: verdict || 'No recommendation recorded.' }],
    },
  ];

  if (confidenceLevel) {
    content.push({
      type: 'panel',
      attrs: { panelType: confidenceToPanelType(confidenceLevel) },
      content: [{
        type: 'paragraph',
        content: [{
          type: 'text',
          text: `Confidence Level: ${confidenceLevel}`,
          marks: [{ type: 'strong' }],
        }],
      }],
    });
  }

  content.push(
    {
      type: 'heading',
      attrs: { level: 2 },
      content: [{ type: 'text', text: 'Rationale & Scribe Notes' }],
    },
    {
      type: 'paragraph',
      content: [{ type: 'text', text: scribeNotes || 'No scribe notes provided.' }],
    },
  );

  if (mustFixIssues.length > 0) {
    content.push({
      type: 'heading',
      attrs: { level: 2 },
      content: [{ type: 'text', text: 'Must-Fix Conditions' }],
    });
    content.push({
      type: 'bulletList',
      content: mustFixIssues.map(issue => ({
        type: 'listItem',
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: issue }],
          },
        ],
      })),
    });
  }

  if (humanJudgementPoints && humanJudgementPoints.length > 0) {
    content.push(
      {
        type: 'heading',
        attrs: { level: 2 },
        content: [{ type: 'text', text: 'Points Requiring Human Judgement' }],
      },
      {
        type: 'bulletList',
        content: humanJudgementPoints.map(point => ({
          type: 'listItem',
          content: [{ type: 'paragraph', content: [{ type: 'text', text: point }] }],
        })),
      },
    );
  }

  content.push(
    {
      type: 'panel',
      attrs: { panelType: 'note' },
      content: [{
        type: 'paragraph',
        content: [{
          type: 'text',
          text: 'Awaiting countersignature by a human architect before this recommendation is finalised.',
        }],
      }],
    },
    { type: 'rule' },
    {
      type: 'paragraph',
      content: [
        {
          type: 'text',
          text: `Requirement: ${requirement}`,
          marks: [{ type: 'strong' }],
        },
      ],
    },
    {
      type: 'paragraph',
      content: [
        {
          type: 'text',
          text: `Generated by ARBoard · Session ID: ${sessionId}`,
          marks: [{ type: 'em' }],
        },
      ],
    },
  );

  return { version: 1, type: 'doc', content };
}

function buildHeaders(email: string, token: string): Record<string, string> {
  const auth = Buffer.from(`${email}:${token}`).toString('base64');
  return {
    Authorization: `Basic ${auth}`,
    'Content-Type': 'application/json',
    Accept: 'application/json',
  };
}

export async function createADRIssue(params: JiraIssueParams): Promise<JiraResult | null> {
  const domain = process.env.JIRA_DOMAIN;
  const email = process.env.JIRA_EMAIL;
  const token = process.env.JIRA_API_TOKEN;
  const projectKey = params.projectKey ?? process.env.JIRA_PROJECT_KEY;

  console.log('[jira] createADRIssue called', {
    domain: domain ?? '(not set)',
    email: email ? email.slice(0, 4) + '…' : '(not set)',
    tokenSet: !!token,
    projectKey: projectKey ?? '(not set)',
    sessionId: params.sessionId,
  });

  if (!domain || !email || !token || !projectKey) {
    console.warn('[jira] env vars not fully configured — skipping Jira write');
    return null;
  }

  const url = `https://${domain}/rest/api/3/issue`;
  const summary = `[ARBoard ADR] ${params.requirement.slice(0, 80)}`;
  const verdictLabel = verdictToLabel(params.verdict);

  const labels = ['arboard-adr', verdictLabel];
  if (params.endorsementType === 'countersigned') labels.push('arboard-signed');

  const fields: Record<string, unknown> = {
    project: { key: projectKey },
    summary,
    issuetype: { name: 'Task' },
    priority: { name: verdictToPriority(params.verdict) },
    labels,
    description: buildADF(params),
  };
  if (params.assigneeAccountId) fields.assignee = { accountId: params.assigneeAccountId };

  const body = { fields };

  const controller = new AbortController();
  const timeout = setTimeout(() => {
    console.error('[jira] fetch timed out after 10s — aborting');
    controller.abort();
  }, 10_000);

  try {
    console.log('[jira] sending POST to', url);

    const response = await fetch(url, {
      method: 'POST',
      headers: buildHeaders(email, token),
      body: JSON.stringify(body),
      signal: controller.signal,
    });

    console.log('[jira] Jira API responded', { status: response.status, ok: response.ok });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(`Jira API ${response.status}: ${text}`);
    }

    const data = (await response.json()) as { key: string };
    console.log('[jira] issue created successfully', { issueKey: data.key });

    if (params.humanJudgementPoints && params.humanJudgementPoints.length > 0) {
      const commentLines = [
        'Points Requiring Human Judgement',
        '',
        ...params.humanJudgementPoints.map(p => `- ${p}`),
      ].join('\n');
      const commentBody = {
        body: {
          version: 1, type: 'doc',
          content: [{
            type: 'paragraph',
            content: [{ type: 'text', text: commentLines }],
          }],
        },
      };
      await fetch(`https://${domain}/rest/api/3/issue/${data.key}/comment`, {
        method: 'POST',
        headers: buildHeaders(email, token),
        body: JSON.stringify(commentBody),
      }).catch(err => { console.warn('[jira] human judgement comment failed:', err); });
    }

    return { issueKey: data.key, issueUrl: `https://${domain}/browse/${data.key}` };
  } finally {
    clearTimeout(timeout);
  }
}

export async function updateADRSignOff(params: {
  issueKey: string;
  architectName: string;
  architectRole: string;
  timestamp: string;
}): Promise<void> {
  const domain = process.env.JIRA_DOMAIN;
  const email = process.env.JIRA_EMAIL;
  const token = process.env.JIRA_API_TOKEN;

  if (!domain || !email || !token) {
    console.warn('[jira] env vars not configured — skipping Jira sign-off update');
    return;
  }

  const headers = buildHeaders(email, token);
  const baseUrl = `https://${domain}/rest/api/3/issue/${params.issueKey}`;

  // Add countersignature as a comment
  const commentBody = {
    body: {
      version: 1,
      type: 'doc',
      content: [
        {
          type: 'panel',
          attrs: { panelType: 'success' },
          content: [{
            type: 'paragraph',
            content: [
              {
                type: 'text',
                text: `Countersigned by: ${params.architectName}, ${params.architectRole}`,
                marks: [{ type: 'strong' }],
              },
              { type: 'hardBreak' },
              {
                type: 'text',
                text: `Timestamp: ${params.timestamp}`,
                marks: [{ type: 'em' }],
              },
            ],
          }],
        },
      ],
    },
  };

  const commentRes = await fetch(`${baseUrl}/comment`, {
    method: 'POST',
    headers,
    body: JSON.stringify(commentBody),
  }).catch(err => { console.error('[jira] comment POST failed:', err); return null; });

  if (commentRes && !commentRes.ok) {
    console.warn('[jira] comment POST returned', commentRes.status);
  }

  // Update labels: GET current labels, add arboard-signed, remove arboard-adr
  const getRes = await fetch(baseUrl, { headers }).catch(() => null);
  if (getRes?.ok) {
    const issueData = (await getRes.json()) as { fields: { labels: string[] } };
    const currentLabels: string[] = issueData.fields.labels ?? [];
    const newLabels = currentLabels.filter(l => l !== 'arboard-adr').concat('arboard-signed');

    await fetch(baseUrl, {
      method: 'PUT',
      headers,
      body: JSON.stringify({ fields: { labels: newLabels } }),
    }).catch(err => { console.error('[jira] label update failed:', err); });
  }
}
